import CharactersList from "@/components/CharactersList";
import { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "NextJS Rick and Morty App",
  description: "Generated by Code Academy Berlin",
};

const charactersPage = () => {
  return (
    <>
      <Link href={"/"}>HOME</Link>
      <h1>Rick & Morty Characters</h1>
      <p>Click a name to checkout details about the character</p>
      <Suspense fallback={<p>Characters are loading</p>}>
        <CharactersList />
      </Suspense>
    </>
  );
};

export default charactersPage;
